global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter-app'
    static_configs:
      - targets: ['65.1.210.41:9100']

  - job_name: 'cadvisor-app'
    static_configs:
      - targets: ['65.1.210.41:8081']

  - job_name: 'website'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://designtechitsolution.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox:9115
